Repository Lonewolf0502/DeveloperCode, pull requests merged in 2022-10, with the labels that each got.

#18 ⭐ Add 2 JAVA question-solution with Good Approach
  Java/Kids_With_the_Greatest_Number_of_Candies.java
  Java/Matrix_Diagonal_Sum.java
Labels: hacktoberfest-accepted

#27 Create TrappingRainWater.cpp
  Leetcode/TrappingRainWater/Solution.cpp
  Leetcode/TrappingRainWater/Statement.md
Labels: enhancement, question, hacktoberfest2022

#34 LeetCode 234: Find palindrome Linked List
  C++/234. Palindrome Linked List.cpp
Labels: Create Proper Description

#37 Created Fizz_Buzz.java
  Java/Fizz_Buzz.java
Labels: hacktoberfest2022

#35 guicalculator.jss(html,css,javascript)
  guicalculator.jss
  guicalculators.jss
Labels: hacktoberfest-accepted, hacktoberfest2022

#24 Create RadixSort.cpp
  C++/RadixSort.cpp
Labels: C++

#45 Reverse a linked list using java #hacktoberfest
  Reverse a linked list using java
Labels: hacktoberfest2022

#44 Reverse a stack using java #hacktoberfest
  Reverse a stack using java
Labels: hacktoberfest2022

#50 Random Advice Generator
  Readme.md
  logo.png
  manifest.json
  popup.html
  script.js
  style.css
Labels: hacktoberfest2022

#48 Two_Sum.java
  Java/Two_Sum.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#40 Add Java Question with proper link and Solution
  Java/Find_the_Highest_Altitude.java
Labels: hacktoberfest2022

#65 added code to send sms using sms_using_python.py
  python/sms_using_python.py
Labels: hacktoberfest2022

#69 added todo_application using reactjs
  Others/todo_application/.gitignore
  Others/todo_application/Readme.md
  Others/todo_application/components/Card.jsx
  Others/todo_application/components/Input.jsx
  Others/todo_application/index.html
  Others/todo_application/package.json
  Others/todo_application/postcss.config.cjs
  Others/todo_application/public/vite.svg
  Others/todo_application/src/App.css
  Others/todo_application/src/App.jsx
  Others/todo_application/src/assets/react.svg
  Others/todo_application/src/main.jsx
  Others/todo_application/tailwind.config.cjs
  Others/todo_application/vite.config.js
  Others/todo_application/yarn.lock
Labels: hacktoberfest2022

#70 Generate a palindrome from the given input
  python/PalindormeGenerator.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#38 Created Valid_Palindrome.java
  Java/Valid_Palindrome.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#71 Created Roman_to_Integer.java
  Java/Roman_to_Integer.java
Labels: hacktoberfest2022

#66 Created Validate_BST.java
  Java/Validate_BST.java
Labels: hacktoberfest2022

#59 Create rabinKarp.java
  Java/rabinKarp.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#78 tower of hanoi }} leetcode question added
  Leetcode/towerofhanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#80 Create SingleNumber.java
  Leetcode/SingleNumber.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#81 python game to guess the jumbled word
  jumbledword.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#84 Added portfolio webpage
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  DeveloperCode.iml
  Others/Shreeyash Garde/achievements.html
  Others/Shreeyash Garde/contact.html
  Others/Shreeyash Garde/css/style.css
  Others/Shreeyash Garde/favicon.ico
  Others/Shreeyash Garde/index.html
  Others/Shreeyash Garde/shreeyash.png
Labels: hacktoberfest-accepted, hacktoberfest2022

#85 Create countdowntimer.py
  python/countdowntimer.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#73 Single Operation Part 1 Solution
  C++/Single_Operation_Part_1.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#92 Added code for leet problem Search in Rotated Sorted Array
  Leetcode/SearchinRotatedSortedArray.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#91 Added LeetCode 124: Binary Tree Max Path Sum
  C++/124_BinaryTreeMaximumPathSum.cpp
Labels: hacktoberfest2022

#93 Rotate matrix problem
  .idea/misc.xml
  .idea/runConfigurations.xml
  DeveloperCode.iml
  Java/Rotate_Matrix_by_90_degree.java
  Leetcode/editDistance.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#98 TechnicalDocumentationPage
  Others/TechnicalDocumentationPage
Labels: hacktoberfest-accepted, hacktoberfest2022

#94 Sudoku Solver.java
  Java/SudokuSolver.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#99 cocktail_sort
  C++/cocktail_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#100 Create scheduling.cpp
  C++/scheduling.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#102 Create CountWords.java
  Java/CountWords.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#103 Added Selection and bubble sort
  C++/BubbleSort.cpp
  C++/SelectionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#101 Create CheckOddEven.java
  Java/CheckOddEven.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#104 Find sqrt of x in python
  python/Sqrt-x.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#3 Create binaryString.java
  Java/binaryString.java
Labels: hacktoberfest2022

#107 create MedianofTwoSortedArrays.cpp file
  Leetcode/MedianofTwoSortedArrays.cpp
Labels: hacktoberfest2022

#108 Create Calculator.java
  Java/Calculator.java
Labels: hacktoberfest2022

#7 Create Combination.java
  Java/Combination.java
Labels: hacktoberfest2022

#4 Create Stairs.java
  Java/Stairs.java
Labels: hacktoberfest2022

#6 Create Stair1.java
  Java/Stair1.java
Labels: hacktoberfest2022

#109 Top k frequent words
  Leetcode/Top K Frequent Words
Labels: hacktoberfest-accepted, hacktoberfest2022

#106 Create heap_sort.cpp
  C++/heap_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#53 Jump Search program
  Java/JumpSearch.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#111 Subsets
  Leetcode/Subsets
Labels: hacktoberfest-accepted, hacktoberfest2022

#115 Create RecursivelySearch.java
  Java/RecursivelySearch.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#8 Create QuickSort.cpp
  C++/QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#9 Create Fibonnaci.java
  Java/Fibonnaci.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#119 Added Sattyam Samania Nft Preview Card Component
  Others/Sattyam Samania Nft preview Card Component/.vscode/settings.json
  Others/Sattyam Samania Nft preview Card Component/README.md
  Others/Sattyam Samania Nft preview Card Component/images/favicon-32x32.png
  Others/Sattyam Samania Nft preview Card Component/images/icon-clock.svg
  Others/Sattyam Samania Nft preview Card Component/images/icon-ethereum.svg
  Others/Sattyam Samania Nft preview Card Component/images/icon-view.svg
  Others/Sattyam Samania Nft preview Card Component/images/image-avatar.png
  Others/Sattyam Samania Nft preview Card Component/images/image-equilibrium.jpg
  Others/Sattyam Samania Nft preview Card Component/index.html
  Others/Sattyam Samania Nft preview Card Component/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#164 weather app using reactJS
  weather app in reactJS/.gitignore
  weather app in reactJS/README.md
  weather app in reactJS/package-lock.json
  weather app in reactJS/package.json
  weather app in reactJS/public/favicon.ico
  weather app in reactJS/public/index.html
  weather app in reactJS/public/logo192.png
  weather app in reactJS/public/logo512.png
  weather app in reactJS/public/manifest.json
  weather app in reactJS/public/robots.txt
  weather app in reactJS/src/App.css
  weather app in reactJS/src/App.js
  weather app in reactJS/src/App.test.js
  weather app in reactJS/src/Components/Style.css
  weather app in reactJS/src/Components/Temp.js
  weather app in reactJS/src/Components/Weathercard.js
  weather app in reactJS/src/index.css
  weather app in reactJS/src/index.js
  weather app in reactJS/src/logo.svg
  weather app in reactJS/src/reportWebVitals.js
  weather app in reactJS/src/setupTests.js
Labels: hacktoberfest2022
